# Compare with Lasso

In [5]:
using AllSum
using GLMNet
using Random
using Distributions

## Simulate data

In [7]:
n = 1000
p = 1000
k = 10

# simulate design matrix and beta
X = randn(n, p)
beta = zeros(p)
beta[1:k] .= rand(Normal(0, 0.5), k)
shuffle!(beta)

# simulate response and compute Z-scores
y = X * beta + 3randn(n)
z = X' * y ./ sqrt(n)

1000-element Vector{Float64}:
 -1.0273672528292863
  3.3323541986760743
 -2.786802968519569
  1.4248014409085357
  0.5398436521433878
  2.2299944511676006
  2.6967957554703292
  1.207743885778079
  1.9810217798055199
  7.085968564651956
 -3.920378525335589
  2.224201077483377
  8.028871952240321
  ⋮
  0.6754744571683196
  2.3757434423188846
 -2.5014873550490995
  2.081488099929415
 -3.0783891261836014
  1.3237010367920414
 -4.476550246429179
  1.4422214707576881
 -0.9750589181259312
  0.45778009997367314
  2.2263630631308535
  0.9451194719145507

## Standard Lasso regression

In [11]:
# cv = glmnetcv(X, y)
beta_hat_lasso = coef(cv)
idx = findall(!iszero, beta)
nz = count(!iszero, beta_hat_lasso)
@show nz
[beta[idx] beta_hat_lasso[idx]]

nz = 41


10×2 Matrix{Float64}:
  0.209104    0.0
 -0.0949044   0.0
  0.490055    0.205092
  0.149518    0.0
  0.55659     0.326932
 -0.874318   -0.569371
 -0.124516    0.0
  0.357384    0.0183492
  0.555637    0.338902
 -1.19906    -0.980606

## AllSum algorithm

In [33]:
lambda0 = 0.1
lambda1 = 0.2
lambda2 = 0.2
R = X' * X / n
sample_sizes = [Float64(n) for i in 1:p]
beta_hat = solve(z, R, lambda0, lambda1, lambda2, sample_sizes)

nz = count(!iszero, beta_hat)
@show nz
[beta[idx] beta_hat[idx]]

nz = 3


10×2 Matrix{Float64}:
  0.209104    0.0
 -0.0949044   0.0
  0.490055    0.0
  0.149518    0.0
  0.55659     0.0
 -0.874318   -0.608614
 -0.124516    0.0
  0.357384    0.0
  0.555637    0.0
 -1.19906    -0.705672